Task 1

In [ ]:
import numpy as np


a = int(input())
b = np.zeros ((a),dtype = int)
for i in range(a) :
  c = int(input())
  b[i] = c

m = np.zeros(a+1,dtype = int)
for i in range (a) :
  m[i] = b[i]

c = int(input())
m[a] = c
print(f'original array : {b}')
print(f'Resized array : {m}')

4
7
1
3
9
5
original array : [7 1 3 9]
Resized array : [7 1 3 9 5]


Task 2

In [ ]:
import numpy as np

n = int(input("Number of entries :"))
arr = np.zeros(n,dtype = int)
for i in range (n) :
  arr[i] = int(input('Elements : '))

print(f'Original Array : {arr}')

new = np.zeros(n,dtype=int)
for j in range(n) :
  if arr [j] <= 0 :
    new[j] = 0
  else :
    new[j] = 1

print(f'After modification : {new} ')

Number of entries :4
Elements : 3
Elements : 4
Elements : -2
Elements : 1
Original Array : [ 3  4 -2  1]
After modification : [1 1 0 1] 


Task 3

In [ ]:
import numpy as np

def reverseArray(arr) :
  a =0
  for i in range (len(arr)//2) :
    a = arr[i]
    arr[i] = arr[len(arr)-1-i]
    arr[len(arr)-1-i] = a

  return arr

In [ ]:
arr = np.array([10,12,20,5,7])
arr = reverseArray(arr)
print(arr)

[ 7  5 20 12 10]


Task 4

In [ ]:
import numpy as np

def printPairs(arr,n) :
  count = 0
  for i in range (len(arr)) :
    for j in range(i+1,len(arr)) :
      if arr[i] + arr[j] == n :
        print (f'{arr[i]} , {arr[j]} ')
        count += 1
      else :
        pass

  if count == 0 :
    print ('No pair found')
  else :
    pass

In [ ]:
arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)


7 , 8 
10 , 5 


In [ ]:
arr2 = np.array([2,-3,1,9,4,5])
printPairs(arr2, 6)


2 , 4 
-3 , 9 
1 , 5 


In [ ]:
arr3 = np.array([5, 9, 7, 6, 10])
printPairs(arr3, 18)


No pair found


Task 5

Input 1

In [ ]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])

Dot_product = 0
for i in range(len(vec1)) :
  a = vec1[i]*vec2[i]
  Dot_product += a

print (f'Dot Product : {Dot_product}')


if Dot_product % 2  == 0 :
  for i in range (len(vec1)) :
    temp = 0
    if i % 2 == 0 :
      temp = vec1[i]
      vec1[i] = vec2[i]
      vec2[i] = temp
    else :
      pass

else :
  for i in range(len(vec1)) :
    temp = 0
    if i % 2 != 0 :
      temp = vec1[i]
      vec1[i] = vec2[i]
      vec1[i] = temp
    else :
      pass
print('After Swapping : ')
print (vec1)
print (vec2)

Dot Product : 32
After Swapping : 
[4 2 6]
[1 5 3]


Input 2

In [ ]:
vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])

Dot_product = 0
for i in range(len(vec1)) :
  a = vec1[i]*vec2[i]
  Dot_product += a

print (f'Dot Product : {Dot_product}')


if Dot_product % 2  == 0 :
  for i in range (len(vec1)) :
    temp = 0
    if i % 2 == 0 :
      temp = vec1[i]
      vec1[i] = vec2[i]
      vec2[i] = temp
    else :
      pass

else :
  for j in range(len(vec1)) :
    temp = 0
    if j % 2 != 0 :
      temp = vec1[j]
      vec1[j] = vec2[j]
      vec2[j] = temp
    else :
      pass
print('After Swapping : ')
print (vec1)
print (vec2)

Dot Product : 95
After Swapping : 
[1 5 3 9]
[4 2 6 7]


Task 6

In [ ]:
import numpy as np

n = int (input('Number of Elements  : '))
arr = np.zeros(n,dtype=int)
for i in range(n) :
  arr[i] = int(input('Enter elements : '))

print(f'Original array : {arr}')
temp = 0
for j in range (len(arr)) :
  for m in range(j+1,len(arr)) :
    if arr[j] < arr[m] :
      pass
    else :
      temp = arr[j]
      arr[j] = arr[m]
      arr [m] = temp

print(f'Sorted array : {arr}')

Number of Elements  : 4
Enter elements : 5
Enter elements : 2
Enter elements : 3
Enter elements : 1
Original array : [5 2 3 1]
Sorted array : [1 2 3 5]


Task 7

In [ ]:
def flatten(arr) :
  a = arr.size
  array = np.zeros(a,dtype=int)
  counter = 0
  for i in range(len(arr)) :
    for j in range (len(arr[i])) :
      array[counter] = arr[i][j]
      counter += 1

  return array

In [ ]:
arr3 = np.array( [ [1, 4],
                   [5, 6],
                   [8, 9] ] )
arr4 = flatten(arr3)
print(arr4)


[1 4 5 6 8 9]


Task 8

In [ ]:
def identity(a) :
  s = a.shape[0]
  flag = True
  for i in range(s) :
    for j in range (s) :
      if a[i][i]!=1 :
        flag= False
        break
      if i!=j :
        if a[i][j] !=0 :
          flag = False
          break
  if flag == True :
    print("Identity Matrix")
  else :
    print("Not an Identity Matrix")

In [ ]:
a = np.array([ [1, 0, 0],
               [0, 1, 0],
               [0, 0, 1] ])
identity(a)

Identity Matrix


Task 9

In [ ]:
def diff(a) :
  prime=0
  second=0
  for i in range (a.shape[0]) :
    prime+=a[i][i]
    second+=a[i][a.shape[0]-1-i]
  diff = prime-second
  diff = abs(diff)
  print(diff)

In [ ]:
a = np.array([ [1,  5,  12,  1],
               [2,  -4,  6,  7],
               [3,  8,  5,  9],
               [3,  5,  23,  -6] ])
diff(a)

22


Task 10.1

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A_T=np.zeros(shape=(A.shape[1],A.shape[0]),dtype=int)
for r in range(A_T.shape[0]):
  for c in range(A_T.shape[1]):
    A_T[r][c]=A[c][r]
print(A_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Task 10.2

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A_T=np.zeros(shape=(A.shape[1],A.shape[0]),dtype=int)
for r in range(A_T.shape[0]):
  for c in range(A_T.shape[1]):
    A_T[r][c]=A[c][r]

A_G=np.zeros(shape=(A_T.shape[0],A.shape[1]),dtype=int)
for r in range(A_G.shape[0]):
  for c in range(A_G.shape[1]):
    sum=0
    for i in range(A_T.shape[1]):
      sum+=A_T[r][i]*A[i][c]
    A_G[r][c]=sum
print(A_G)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


Task 11

In [ ]:
A = np.array([[4,1,2],
              [9,3,7]])
M,N = A.shape[0],A.shape[1]
diff = abs(M-N)
m= diff % M
sum = 0
for i in range(N):
  sum+=A[m][i]
avg=sum/N
avg=round(avg,2)
B=np.zeros(shape=(M,N),dtype=float)
for r in range(M):
  for c in range(N):
    B[r][c]=A[r][c]*avg
print(B)

[[25.32  6.33 12.66]
 [56.97 18.99 44.31]]
